
export const issueBook = async (req, res) => {
    try {
      // Logic to issue a book
    } catch (error) {
      res.status(500).json({ message: error.message });
    }
  };
  
  export const returnBook = async (req, res) => {
    try {
      // Logic to return a book
    } catch (error) {
      res.status(500).json({ message: error.message });
    }
  };
  
  export const getTransactionDetailsByBook = async (req, res) => {
    try {
      // Logic to get transaction details by book name
    } catch (error) {
      res.status(500).json({ message: error.message });
    }
  };
  
  export const getTotalRentByBook = async (req, res) => {
    try {
      // Logic to get total rent generated by a book
    } catch (error) {
      res.status(500).json({ message: error.message });
    }
  };
  
  export const getBooksIssuedToUser = async (req, res) => {
    try {
      // Logic to get books issued to a user
    } catch (error) {
      res.status(500).json({ message: error.message });
    }
  };
  
  export const getBooksIssuedInDateRange = async (req, res) => {
    try {
      // Logic to get books issued in a date range
    } catch (error) {
      res.status(500).json({ message: error.message });
    }
  };